POM: update parent to pom-scijava 40.0.0
This updates the ImgLib2 dependencies to build on imglib2 v7.
A rebuild is needed to avoid:

  [ERROR] Command errored: Open in ClearVolume
  java.lang.NoSuchMethodError: net.imglib2.view.Views.flatIterable(Lnet/imglib2/RandomAccessibleInterval;)Lnet/imglib2/IterableInterval;
    at de.mpicbg.jug.clearvolume.ImgLib2ClearVolume.copy(ImgLib2ClearVolume.java:461)

As reported in https://forum.image.sc/t/108806.